{
  "swagger": "2.0",
  "info": {
    "title": "onePlace XI Core",
    "version": "1.1.1",
    "description": "This is the onePlace XI Core API Server for Swissfaucet.io"
  },
  "schemes": [
    "https",
    "http"
  ],
  "host": "xi.api.swissfaucet.io",
  "tags": [
    {
      "name": "Status",
      "description": "Create, manipulate, and retrieve status messages."
    },
    {
      "name": "Ping"
    },
    {
      "name": "User"
    },
    {
      "name": "Faucet",
      "description": "Faucet API"
    },
    {
      "name": "Shortlink",
      "description": "Shortlink API"
    },
    {
      "name": "Lottery",
      "description": "Lottery API"
    },
    {
      "name": "Guild",
      "description": "Guild API"
    },
    {
      "name": "Login",
      "description": "Login with Username and Password"
    }
  ],
  "securityDefinitions": {
    "OAuth2" : {
      "type" : "oauth2",
      "authorizationUrl": "http://xi.api.swissfaucet.io/oauth/authorize",
      "tokenUrl": "http://xi.api.swissfaucet.io/oauth",
      "flow": "accessCode",
      "description": "You have to use /login first to get a user session. Then get code from Authorization and finally the Token with the Code.",
      "name": "token",
      "in": "header",
      "scopes": {
        "read": "Grants read access",
        "write": "Grants write access",
        "admin": "Grants read and write access to administrative information"
      }
    }
  },
  "paths": {
    "/status": {
      "get": {
        "tags": [
          "Status"
        ],
        "description": "Retrieve a paginated list of status messages.",
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "tags": [
          "Status"
        ],
        "description": "Create a new status messages.",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/status/{status_id}": {
      "get": {
        "tags": [
          "Status"
        ],
        "description": "Retrieve a status message.",
        "parameters": [
          {
            "in": "path",
            "name": "status_id",
            "description": "URL parameter status_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          }
        ],
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "patch": {
        "tags": [
          "Status"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Update a status message.",
        "parameters": [
          {
            "in": "path",
            "name": "status_id",
            "description": "URL parameter status_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "put": {
        "tags": [
          "Status"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Replace a status message.",
        "parameters": [
          {
            "in": "path",
            "name": "status_id",
            "description": "URL parameter status_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        ],
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "delete": {
        "tags": [
          "Status"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Delete a status message.",
        "parameters": [
          {
            "in": "path",
            "name": "status_id",
            "description": "URL parameter status_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          }
        ],
        "produces": [
          "application/vnd.status.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/ping": {
      "get": {
        "tags": [
          "Ping"
        ],
        "summary": "Check alive",
        "produces": [
          "application/vnd.status.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/user": {
      "get": {
        "summary": "Get User Info",
        "tags": [
          "User"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "produces": [
          "application/vnd.user.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/UserInfo"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Login"
        ],
        "description": "Perform Login Action",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Login"
            }
          }
        ],
        "produces": [
          "application/vnd.user.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "user_id": {
                  "type": "string"
                }
              },
              "example": {
                "user_id": "1"
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          }
        }
      }
    },
    "/achievement": {
      "get": {
        "tags": [
          "Faucet"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "platform",
            "required": true,
            "schema": {
              "$ref": "#/definitions/platform"
            }
          }
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get a List of all available Achievements",
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AchievementList"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/achievement/{achievement_id}": {
      "put": {
        "tags": [
          "Faucet"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Claim a complete Achievement for a User",
        "parameters": [
          {
            "in": "path",
            "name": "achievement_id",
            "description": "URL parameter achievement_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Achievement"
            }
          }
        ],
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/dailytask": {
      "get": {
        "tags": [
          "Faucet"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "platform",
            "required": true,
            "schema": {
              "$ref": "#/definitions/platform"
            }
          }
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get a List of all Dailytasks",
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/DailytaskList"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/dailytask/{dailytask_id}": {
      "put": {
        "tags": [
          "Faucet"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Claim a complete dailytask for a user",
        "parameters": [
          {
            "in": "path",
            "name": "dailytask_id",
            "description": "URL parameter dailytask_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Dailytask"
            }
          }
        ],
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": [],
              "example": []
            }
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          }
        }
      }
    },
    "/claim": {
      "get": {
        "tags": [
          "Faucet"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get Timer for next Claim",
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "tags": [
          "Faucet"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Request Claim",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Claim"
            }
          }
        ],
        "produces": [
          "application/vnd.faucet.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "201": {
            "description": "Created"
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/shortlink": {
      "get": {
        "tags": [
          "Shortlink"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get a List of all Shortlink Providers",
        "produces": [
          "application/vnd.shortlink.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ShortlinkList"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/shortlink/{shortlink_id}": {
      "put": {
        "tags": [
          "Shortlink"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Claim a complete Shortlink",
        "parameters": [
          {
            "in": "path",
            "name": "shortlink_id",
            "description": "URL parameter shortlink_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          }
        ],
        "produces": [
          "application/vnd.shortlink.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "get": {
        "tags": [
          "Shortlink"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get the basic information and links for a shortlink provider",
        "parameters": [
          {
            "in": "path",
            "name": "shortlink_id",
            "description": "URL parameter shortlink_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          }
        ],
        "produces": [
          "application/vnd.shortlink.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ShortlinkLink"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/lottery/round": {
      "get": {
        "tags": [
          "Lottery"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Current lottery round",
        "produces": [
          "application/vnd.lottery.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/LotteryRound"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/lottery/tickets": {
      "post": {
        "tags": [
          "Lottery"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Buy Lottery Tickets",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Tickets"
            }
          }
        ],
        "produces": [
          "application/vnd.lottery.v1+json",
          "application/json",
          "application/*+json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/TicketsResponse"
            }
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/guild": {
      "get": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get List of all Guilds",
        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Guild"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/guild/leave": {
      "delete": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Leave Guild",

        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Not Found",
                "status": 404,
                "detail": "User is not part of any guild."
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Forbidden",
                "status": 403,
                "detail": "You cannot leave the guild as guildmaster. Please promote a new guildmaster first"
              }
            }
          }
        }
      }
    },
    "/guild/remove": {
      "delete": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Remove Guild",

        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Not Found",
                "status": 404,
                "detail": "User is not part of any guild."
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Forbidden",
                "status": 403,
                "detail": "You must own a guild to delete it."
              }
            }
          }
        }
      }
    },
    "/guild/join": {
      "put": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Join a guild",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GuildJoin"
            }
          }
        ],
        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "state": "success",
                "message": "Successfully sent a join request to guild Custom Miners. Please wait for approval by guild.",
                "_links": {
                  "self": {
                    "href": "http://xi.api.swissfaucet.io/guild/join"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Not Found",
                "status": 404,
                "detail": "The guild you want to join does not exist"
              }
            }
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Forbidden",
                "status": 403,
                "detail": "You have reached the limit of 5 guild join requests. Wait for approval or cancel requests."
              }
            }
          }
        }
      }
    },
    "/guild/create": {
      "post": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Create a new Guild",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GuildNew"
            }
          }
        ],
        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "string"
                },
                "owner_idfs": {
                  "type": "string"
                },
                "created_date": {
                  "type": "string"
                },
                "xp_level": {
                  "type": "integer"
                },
                "xp_current": {
                  "type": "integer"
                },
                "xp_total": {
                  "type": "integer"
                },
                "icon": {
                  "type": "string"
                },
                "is_vip": {
                  "type": "integer"
                },
                "token_balance": {
                  "type": "integer"
                },
                "_links": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "label": "Praesis Castle",
                "created_date": "2021-05-04 23:15:12",
                "xp_level": 1,
                "xp_current": 0,
                "xp_total": 0,
                "icon": "some-icon",
                "is_vip": 0,
                "token_balance": 0,
                "owner": {
                  "id": "335874987",
                  "name": "Praesidiarius",
                  "token_balance": 65836
                },
                "_links": {
                  "self": {
                    "href": "http://xi.api.swissfaucet.io/guild/create"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          }
        }
      }
    },
    "/guild/update": {
      "patch": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "summary": "Update Guild",
        "description": "Update Guild. You can update all settings or only one at a time, all parameters are optional",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GuildUpdate"
            }
          }
        ],
        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "Guild_ID": {
                  "type": "integer"
                },
                "label": {
                  "type": "string"
                },
                "owner_idfs": {
                  "type": "integer"
                },
                "created_date": {
                  "type": "string"
                },
                "xp_level": {
                  "type": "integer"
                },
                "xp_current": {
                  "type": "integer"
                },
                "xp_total": {
                  "type": "integer"
                },
                "icon": {
                  "type": "string"
                },
                "is_vip": {
                  "type": "integer"
                },
                "token_balance": {
                  "type": "integer"
                },
                "_links": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "object",
                      "properties": {
                        "href": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "label": "Praesis Castle",
                "created_date": "2021-05-04 23:15:12",
                "xp_level": 1,
                "xp_current": 0,
                "xp_total": 0,
                "icon": "some-icon",
                "is_vip": 0,
                "token_balance": 0,
                "owner": {
                  "id": "335874987",
                  "name": "Praesidiarius",
                  "token_balance": 65836
                },
                "_links": {
                  "self": {
                    "href": "http://xi.api.swissfaucet.io/guild/update"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "examples": {
              "application/json": {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Not Found",
                "status": 404,
                "detail": "You are not guildmaster of any guild"
              }
            }
          },
          "400": {
            "description": "Client Error"
          },
          "422": {
            "description": "Unprocessable Entity"
          }
        }
      }
    },
    "/guild/{guild_id}": {
      "get": {
        "tags": [
          "Guild"
        ],
        "security": [
          {"OAuth2" : []}
        ],
        "description": "Get Guild Information",
        "parameters": [
          {
            "in": "path",
            "name": "guild_id",
            "description": "URL parameter guild_id",
            "type": "string",
            "required": true,
            "minimum": 0,
            "maximum": 1
          }
        ],
        "produces": [
          "application/vnd.guild.v1+json",
          "application/hal+json",
          "application/json"
        ],
        "responses": {
          "406": {
            "description": "Not Acceptable"
          },
          "415": {
            "description": "Unsupported Media Type"
          },
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    }
  },
  "definitions": {
    "platform": {
      "type": "string",
      "description": "Desired Platform (website|app)",
      "required": [
        "platform"
      ]
    },
    "GuildJoin": {
      "type": "object",
      "properties": {
        "guild": {
          "type": "integer",
          "description": "Guild ID"
        }
      },
      "example": {
        "guild": 1
      }
    },
    "GuildUpdate": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of Guild"
        },
        "icon": {
          "type": "string",
          "description": "Guild Icon"
        }
      },
      "example": {
        "name": "Praesis Castle"
      }
    },
    "GuildNew": {
      "type": "object",
      "properties": {
        "guild": {
          "type": "string",
          "description": "Guild ID"
        },
        "name": {
          "type": "string",
          "description": "Name of Guild"
        },
        "icon": {
          "type": "string",
          "description": "Guild Icon"
        }
      },
      "example": {
        "name": "Praesis Castle",
        "icon": "fas fa-crown"
      }
    },
    "Guild": {
      "type": "object",
      "example": {
        "_links": {
          "self": {
            "href": "http://xi.api.swissfaucet.io/guild"
          }
        },
        "_embedded": {
          "guild": [
            {
              "Guild_ID": "1",
              "label": "Founder Edition",
              "owner_idfs": "335874988",
              "created_date": "2021-04-08 01:50:20",
              "xp_level": "1",
              "xp_current": "142",
              "xp_total": "0",
              "icon": "fas fa-crown",
              "is_vip": "1",
              "token_balance": "0",
              "members": 120
            },
            {
              "Guild_ID": "2",
              "label": "infiniteLife",
              "owner_idfs": "335874994",
              "created_date": "2021-04-09 04:01:52",
              "xp_level": "1",
              "xp_current": "0",
              "xp_total": "0",
              "icon": "fas fa-shield-alt",
              "is_vip": "0",
              "token_balance": "0",
              "members": 4
            }
          ]
        },
        "total_items": 2
      }
    },
    "Tickets": {
      "type": "object",
      "properties": {
        "round": {
          "type": "integer",
          "description": "Lottery Round ID"
        },
        "tickets": {
          "type": "integer",
          "description": "Amount of tickets to buy"
        }
      },
      "required": [
        "round",
        "tickets"
      ],
      "example": {
        "round": 1,
        "tickets": 10
      }
    },
    "TicketsResponse": {
      "type": "object",
      "example": {
        "state": "success",
        "message": "10 bought for round 1",
        "user": {
          "name": "Testuser",
          "balance": 100,
          "tickets": 10
        }
      }
    },
    "Achievement": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "description": "The Platform for the Dailytasks"
        }
      },
      "required": [
        "platform"
      ]
    },
    "LotteryRound": {
      "type": "object",
      "example": {
        "Round_ID": "3",
        "server_hash": "",
        "date_started": "2021-04-25 18:00:01",
        "date_end": "2021-05-02 18:00:01",
        "winners_last_round": [
          {
            "name": "hamazi",
            "id": "335878708",
            "rank": "1",
            "coins_won": "128744",
            "tickets": "87"
          },
          {
            "name": "Mizie",
            "id": "335877443",
            "rank": "2",
            "coins_won": "36784",
            "tickets": "100"
          },
          {
            "name": "antia",
            "id": "335878903",
            "rank": "3",
            "coins_won": "18392",
            "tickets": "1477"
          }
        ],
        "my_tickets": 0,
        "my_chance": 0,
        "tickets": 4108
      }
    },
    "AchievementList": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "description": "The Platform for the Dailytasks"
        }
      },
      "example": {
        "_links": {
          "self": {
            "href": "http://xi.api.swissfaucet.io/achievement"
          }
        },
        "_embedded": {
          "achievement": [
            {
              "Achievement_ID": "1",
              "label": "Reach Level 10",
              "goal": "10",
              "reward": "100",
              "type": "xplevel",
              "mode": "global"
            },
            {
              "Achievement_ID": "2",
              "label": "Reach Level 25",
              "goal": "25",
              "reward": "250",
              "type": "xplevel",
              "mode": "global"
            }
          ]
        },
        "total_items": 2
      },
      "required": [
        "platform"
      ]
    },
    "Dailytask": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "description": "The Platform for the Dailytasks"
        }
      },
      "required": [
        "platform"
      ]
    },
    "DailytaskList": {
      "type": "object",
      "properties": {
        "platform": {
          "type": "string",
          "description": "The Platform for the Dailytasks"
        }
      },
      "example": {
        "_links": {
          "self": {
            "href": "http://xi.api.swissfaucet.io/dailytask"
          }
        },
        "_embedded": {
          "dailytask": [
            {
              "Dailytask_ID": "1",
              "label": "Complete 5 Shortlinks",
              "goal": "5",
              "reward": "10",
              "type": "shortlink",
              "sort_id": "0",
              "mode": "website"
            },
            {
              "Dailytask_ID": "2",
              "label": "Complete 10 Shortlinks",
              "goal": "10",
              "reward": "20",
              "type": "shortlink",
              "sort_id": "1",
              "mode": "website"
            }
          ]
        },
        "total_items": 2
      },
      "required": [
        "platform"
      ]
    },
    "ShortlinkLink": {
      "type": "object",
      "example": {
        "Shortlink_ID": "2",
        "label": "Exe.io",
        "url": "exe-io",
        "description": "",
        "reward": "25",
        "cpm": "1.5",
        "active": "1",
        "link": {
          "shortlink_idfs": "2",
          "href": "https://exe.io/CgS1B",
          "link_id": "HoEUCWmcDEf2YK4fR0S81ej2PDNmTqrm3OgZe39ico66HCuxbOy"
        },
        "_links": {
          "self": {
            "href": "http://xi.api.swissfaucet.io/shortlink/2"
          }
        }
      }
    },
    "ShortlinkList": {
      "type": "object",
      "example": {
        "_links": {
          "self": {
            "href": "http://xi.api.swissfaucet.io/shortlink"
          }
        },
        "_embedded": {
          "shortlink": [
            {
              "provider": [
                {
                  "Shortlink_ID": "1",
                  "label": "FC.lc",
                  "url": "fc-lc",
                  "description": "",
                  "reward": "15",
                  "cpm": "3",
                  "active": "1",
                  "linksTotal": 1,
                  "linksDone": 0,
                  "count_complete": 13353,
                  "count_started": 2267
                },
                {
                  "Shortlink_ID": "2",
                  "label": "Exe.io",
                  "url": "exe-io",
                  "description": "",
                  "reward": "25",
                  "cpm": "1.5",
                  "active": "1",
                  "linksTotal": 1,
                  "linksDone": 0,
                  "count_complete": 8509,
                  "count_started": 853
                }
              ],
              "total_reward": 40,
              "total_links": 2
            }
          ]
        },
        "total_items": 1
      }
    },
    "Claim": {
      "type": "object"
    },
    "User": {
      "type": "object",
      "properties": {
        "user": {
          "type": "string",
          "description": "The user submitting the status message."
        }
      },
      "required": [
        "user"
      ]
    },
    "Login": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "description": "Name or E-Mail for User"
        },
        "password": {
          "type": "string",
          "description": "Password for user"
        }
      },
      "required": [
        "username",
        "password"
      ],
      "example": {
        "username": "Username for User you want to login",
        "password": "Password for the user"
      }
    },
    "Status": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "description": "A status message of no more than 140 characters"
        },
        "user": {
          "type": "string",
          "description": "The user submitting the status message."
        },
        "timestamp": {
          "type": "string",
          "description": "The timestamp when the status message was last modified."
        }
      },
      "required": [
        "message",
        "user"
      ]
    },
    "UserInfo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Client ID for the User."
        },
        "username": {
          "type": "string",
          "description": "The username for the User."
        },
        "token_balance": {
          "type": "number",
          "description": "The current token balance for the User."
        },
        "xp_level": {
          "type": "integer",
          "description": "Current XP Level for the User."
        },
        "xp_percent": {
          "type": "integer",
          "description": "Current % for next XP Level for the User."
        }
      },
      "example": {
        "id": 1,
        "username": "testuser",
        "token_balance": 50.00,
        "xp_level": 1,
        "xp_percent": 85
      }
    }
  }
}